# Generated by Django 3.0.2 on 2020-11-28 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orientacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encontros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do encontro')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição breve do encontro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('orientacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orientacao.Orientacao', verbose_name='Orientação:')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
