# Generated by Django 3.0.2 on 2020-11-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encontros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encontros',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data da reunião'),
        ),
    ]
